In [79]:
"""INTRODUCTION TO PYTHON FOR MACHINE LEARNING GRADED QUIZ BY JOE IROEGBU"""

'INTRODUCTION TO PYTHON FOR MACHINE LEARNING GRADED QUIZ BY JOE IROEGBU'

In [ ]:
# Load Libraries

In [80]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [2]:
#Load Dataset

In [3]:
Data = pd.read_csv("https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")
Data.head()

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

# Question 2

In [5]:
array_new=np.identity(3)
print('3x3 matrix:')

3x3 matrix:


In [6]:
print(array_new)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Question 6


In [7]:
#feature with missing values and total number of missing values
Data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [77]:
"""from the result above,the fuel_unit has missing values and total number of missing value is 180"""

'from the result above,the fuel_unit has missing values and total number of missing value is 180'

In [31]:
# to check the percentage of the missing rows
# lets check the total number of rows
total_no_of_rows = Data['fuel_unit'].count()
total_no_of_rows

29523

In [33]:
total_no_of_missing_value = 180
percentage_of_missing_rows = (total_no_of_missing_value/total_no_of_rows) * 100
percentage_of_missing_rows

0.609694136774718

In [64]:
print("round(0.609694136774718, 3):", round(0.609694136774718,3))

round(0.609694136774718, 3): 0.61


# Question 7

In [34]:
# Lets check for the category for the feature with missing values
Data.groupby( 'fuel_unit' )[ 'fuel_unit' ].count() 

fuel_unit
bbl        7998
gal          84
gramsU      464
kgU         110
mcf       11534
mmbtu       180
mwdth        95
mwhth       100
ton        8958
Name: fuel_unit, dtype: int64

In [78]:
"""From the result above, we can see that the feature above has nine different units of measurement. A feature can either be numerical or categorical. So in this case the fuel unit is categorical"""

'From the result above, we can see that the feature above has nine different units of measurement. A feature can either be numerical or categorical. So in this case the fuel unit is categorical'

In [8]:
#missing value imputation technique to use here is mode
Data['fuel_unit'].fillna(Data['fuel_unit'].mode()[0], inplace = True)

In [9]:
#check if missing values are still there
print(Data.isnull().sum()) 

record_id                       0
utility_id_ferc1                0
report_year                     0
plant_name_ferc1                0
fuel_type_code_pudl             0
fuel_unit                       0
fuel_qty_burned                 0
fuel_mmbtu_per_unit             0
fuel_cost_per_unit_burned       0
fuel_cost_per_unit_delivered    0
fuel_cost_per_mmbtu             0
dtype: int64


In [70]:
"""The missing values have been taken care of with the mode() function"""

'The missing values have been taken care of with the mode() function'

# Question 1

In [14]:
A = [1,2,3,4,5,6] 
B = [13, 21, 34]
A.extend(B) 
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


# Question 5

In [15]:
# checking for skewness
Data['fuel_qty_burned' ].skew() 

15.851495469109503

In [65]:
# Round up to 2 decimal places
print("round(15.851495469109503, 2):", round(15.851495469109503,2))

round(15.851495469109503, 2): 15.85


In [16]:
#checking for kurtosis
Data['fuel_qty_burned'].kurt() 

651.3694501337732

In [66]:
# Round up to 2 decimal places
print("round(651.3694501337732, 2):", round(651.3694501337732,2))

round(651.3694501337732, 2): 651.37


# Question 4

In [17]:
# Finding the standard deviation for fuel_mmbtu_per_unit
Data['fuel_mmbtu_per_unit' ].std() 

10.600220307806886

In [67]:
# Round up to 2 decimal places
print("round(10.600220307806886, 2):", round(10.600220307806886,2))

round(10.600220307806886, 2): 10.6


In [18]:
# Finding the 75th percentile for fuel_mmbtu_per_unit
percentile = Data['fuel_mmbtu_per_unit'].quantile(q=0.75, interpolation='linear')
percentile

17.006

In [68]:
# Round up to 2 decimal places
print("round(17.006, 2):", round(17.006,2))

round(17.006, 2): 17.01


# Question 3

In [38]:
# To find the fuel type code that has the lowest average fuel cost per unit burned
# We first sort out the various fuel types in the dataset
Data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean()

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

In [39]:
#lets sort the values
Data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean().sort_values()

fuel_type_code_pudl
gas          13.659397
other        18.253856
waste        19.518122
coal         67.421830
oil         168.877086
nuclear    4955.157002
Name: fuel_cost_per_unit_burned, dtype: float64

In [43]:
"""So from the result above we can deduce that the fuel type code with the lowest average fuel cost per unit burned is GAS"""

'So from the result above we can deduce that the fuel type code with the lowest average fuel cost per unit burned is GAS'

# Question 8

In [ ]:
# To find features with the second and third lowest correlation with the fuel cost per unit burned

In [45]:
Data.corr('spearman').loc['fuel_cost_per_unit_burned'].sort_values()

fuel_qty_burned                -0.390275
utility_id_ferc1               -0.074844
report_year                     0.233647
fuel_cost_per_mmbtu             0.318533
fuel_mmbtu_per_unit             0.557998
fuel_cost_per_unit_delivered    0.760263
fuel_cost_per_unit_burned       1.000000
Name: fuel_cost_per_unit_burned, dtype: float64

In [56]:
"""From the result above I went for fuel_mmbtu_per_unit and fuel_cost_per_unit_delivered"""

'From the result above I went for fuel_mmbtu_per_unit and fuel_cost_per_unit_delivered'

# Question 9

In [54]:
 yearly_cost = Data.groupby(['report_year', 'fuel_type_code_pudl'])[ 'fuel_cost_per_unit_burned'].sum() 

In [47]:
yearly_cost

report_year  fuel_type_code_pudl
1994         coal                   475
             gas                    487
             nuclear                 71
             oil                    166
             other                   12
                                   ... 
2018         coal                   211
             gas                    450
             nuclear                 20
             oil                    254
             waste                   16
Name: fuel_cost_per_unit_burned, Length: 148, dtype: int64

In [72]:
# To find the percentage change in the fuel cost per unit in 1998 compared to 1994 for fuel type, coal
year_1994, year_1998 = yearly_cost.loc[[1994, 1998], 'coal']
percentage_change = ((year_1998 - year_1994)/ year_1994) * 100
percentage_change

-20.56765451826049

In [76]:
# Round up to a whole number
print("round(-20.56765451826049):", round(-20.56765451826049))

round(-20.56765451826049): -21


# Question 10

In [51]:
Data.groupby('report_year') [ 'fuel_cost_per_unit_delivered'].mean()

report_year
1994       63.636060
1995       32.735269
1996     9196.705948
1997    11140.197239
1998      287.154420
1999       25.551627
2000      985.362877
2001       60.050396
2002       47.594361
2003       55.663493
2004      139.524275
2005       41.438184
2006       38.657484
2007       43.325023
2008       58.588197
2009      652.694163
2010       91.862105
2011       59.774667
2012       60.994502
2013      172.307591
2014      192.737183
2015      326.535511
2016      103.901761
2017       46.196861
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64

In [52]:
# Lets sort the values
Data.groupby('report_year') [ 'fuel_cost_per_unit_delivered'].mean().sort_values(ascending=False)

report_year
1997    11140.197239
1996     9196.705948
2000      985.362877
2009      652.694163
2018      499.269966
2015      326.535511
1998      287.154420
2014      192.737183
2013      172.307591
2004      139.524275
2016      103.901761
2010       91.862105
1994       63.636060
2012       60.994502
2001       60.050396
2011       59.774667
2008       58.588197
2003       55.663493
2002       47.594361
2017       46.196861
2007       43.325023
2005       41.438184
2006       38.657484
1995       32.735269
1999       25.551627
Name: fuel_cost_per_unit_delivered, dtype: float64

In [69]:
"""We can see from the result above that the year that has the highest average fuel cost per unit delivered if 1997"""

'We can see from the result above that the year that has the highest average fuel cost per unit delivered if 1997'